### ISSUE TITLE
Old lists not downloadable

### ISSUE THREAD

**Issue by rflume** [DistriNet/tranco-python-package#1]
Hi, 

when I try to download the list from 01 Jan. 2019 I get an `BadZipFile("File is not a zip file")` error.
I can, however, directly download the list (`.csv file`) from the website.

The code to download the list is the following:

```
from tranco import Tranco

t = Tranco(cache=True, cache_dir='.tranco')
list_jan = t.list('2019-01-01')
```

The same error occurs for the list of `2019-02-01` while retreiving `2019-01-01` (and any list after that) works as expected.

Is there a workaround to fix this, like downloading the `csv` file directly through the Tranco module?

Thanks!

**Comment by VictorLeP** [comment]
Thank you for notifying us of this issue! Older lists are not available as ZIP files, but I've now added a fallback that will directly download the csv in such cases.

**Comment by rflume** [comment]
Thank you for the quick fix!
