### ISSUE TITLE
Incorrect loading of not full list

### ISSUE THREAD

**Issue by maxzhenzhera** [DistriNet/tranco-python-package#10]
The code here does not strip newlines on not full loading: 
https://github.com/DistriNet/tranco-python-package/blob/f29ef30316c1c77acde05de7c0ac83929901565d/tranco/tranco.py#L129-L133

**Comment by maxzhenzhera** [comment]
Therefore, `TrancoList` contains a list of domains with `\n`.

**Comment by VictorLeP** [comment]
Thank you for the report and fix! I merged your PR into [version 0.8.1](https://pypi.org/project/tranco/0.8.1/).
