### ISSUE TITLE
Is Tranco dead?

### ISSUE THREAD

**Issue by warburtr0n** [DistriNet/tranco-python-package#6]
The lists are currently unavailable to download via the website and, having just installed the Python package, I am getting errors which seem to imply it can't connect to or read from the online lists.

The website link for the up to date list gives a Cloudflare 502 error.

The permalink to https://tranco-list.eu/top-1m.csv.zip DOES work but I'm concerned it may not actually be up to date since it's not timestamped.

**Comment by Derekt2** [comment]
I'm able to pull older dates ` latest_list = Tranco(cache=True).list(date='2019-02-25') `
but doing `latest_list = Tranco(cache=True).list()` currently fails for me as there is no response

**Comment by VictorLeP** [comment]
Thanks for the notification. The file should be available again.

As noted on the home page of the website, the `Last-Modified` header provides an exact timestamp for when the file was updated (when following the redirects).

**Comment by warburtr0n** [comment]
Awesome, thanks so much for the quick response!
