### ISSUE TITLE
def rank(self, domain) implementation is pretty slow

### ISSUE THREAD

**Issue by jconwell** [DistriNet/tranco-python-package#7]
the rank() function uses `list.index()` to get the rank of any passed in domain. This causes a linear scan through the list until if finds the domain, which can take a long time if used to look up ranks for a large set of domains. 

Instead you might build a dict[domain:rank] to hold the domain ranks. This way each rank lookup is a simple hashtable lookup.

If you want I can create a PR for you to do this.

**Comment by VictorLeP** [comment]
> If you want I can create a PR for you to do this.

That would be great, thanks!

**Comment by jconwell** [comment]
I sent the PR. Hope this helps

**Comment by VictorLeP** [comment]
Improved in [675a86d](https://github.com/DistriNet/tranco-python-package/commit/675a86dfcae99c840ceb610d25cd66129cfeac79)
